# # Golang CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-go/ for more details

version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:10.12
        # environment: # environment variables for primary container
          # POSTGRES_PASSWORD: test1234
          # POSTGRES_USER: circleci-demo-go
          # POSTGRES_DB: circleci-demo-go
    steps:
      - checkout
      - run:
          name: Add user to Postgres db
          command: |
            sudo -u postgres psql
            create database myuser;
            create user myuser with encrypted password 'mypass';
            grant all privileges on database mydb to myuser;
      - run:
          name: Download dependencies
          command: |
            go mod download
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run unit tests
          environment: # environment variables for the database url and path to migration files
            DBPASSWORD: mypass
            DBUSER: myuser
            HOSTIP: localhost
            # DBPASSWORD: ""
          # Store the results of our tests in the $TEST_RESULTS directory
          command: |
            go test -v
      # # specify any bash command here prefixed with `run: `

  deploy:
    machine: true
    steps:
      - heroku/deploy-via-git
  #### TEMPLATE_NOTE: go expects specific checkout path representing url
  #### expecting it in the form of
  ####   /go/src/github.com/circleci/go-tool
  ####   /go/src/bitbucket.org/circleci/go-tool
  # working_directory: /go/src/github.com/RizkyRajitha/goherokudemo
  #   - run:
  #     name: Start service
  #     environment:
  #       DBPASSWORD: test1234
  #       DBUSER: circleci-demo-go
  #       HOSTIP: localhost
  #     command: go run main.go
  #     background: true # keep service running and proceed to next step
  #   - run:
  #       name: Validate service is working
  #       command: |
  #         sleep 5
  #         curl --retry 10 --retry-delay 1 -X GET --header "Content-Type: plain/html"  http://localhost:8080/

workflows:
  version: 2
  # Workflow name
  build:
    jobs:
      - build
      - deploy:
          requires:
            # Run after all tests have passed
            - build
          filters:
            branches:
              # Only deploy on pushes to the master branch
              only: master
# workflows:
# heroku_deploy:
#   jobs:
#     - heroku/deploy-via-git
